import sys
import unittest
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.build_parlay_board import build_parlay_board


class ParlayBoardTests(unittest.TestCase):
    def test_build_parlay_board_creates_best_value_3_to_5_leg_sets(self) -> None:
        report = pd.DataFrame(
            [
                {
                    "event_name": "Test Event",
                    "fighter_a": "Alpha",
                    "fighter_b": "Beta",
                    "fight_key": "alpha||beta",
                    "chosen_value_expression": "Alpha moneyline",
                    "effective_american_odds": -135,
                    "effective_projected_prob": 0.64,
                    "effective_implied_prob": 0.5745,
                    "effective_edge": 0.0655,
                    "model_confidence": 0.76,
                    "data_quality": 0.96,
                    "bet_quality_score": 88.0,
                    "recommended_tier": "A",
                    "recommended_action": "Bettable now",
                    "fragility_bucket": "low",
                    "selection_fallback_used": 0.0,
                    "market_blend_weight": 0.18,
                    "chosen_expression_stake": 30.0,
                },
                {
                    "event_name": "Test Event",
                    "fighter_a": "Gamma",
                    "fighter_b": "Delta",
                    "fight_key": "gamma||delta",
                    "chosen_value_expression": "Gamma moneyline",
                    "effective_american_odds": +120,
                    "effective_projected_prob": 0.50,
                    "effective_implied_prob": 0.4545,
                    "effective_edge": 0.0455,
                    "model_confidence": 0.70,
                    "data_quality": 0.94,
                    "bet_quality_score": 80.0,
                    "recommended_tier": "A",
                    "recommended_action": "Bettable now",
                    "fragility_bucket": "low",
                    "selection_fallback_used": 0.0,
                    "market_blend_weight": 0.12,
                    "chosen_expression_stake": 24.0,
                },
                {
                    "event_name": "Test Event",
                    "fighter_a": "Epsilon",
                    "fighter_b": "Zeta",
                    "fight_key": "epsilon||zeta",
                    "chosen_value_expression": "Epsilon moneyline",
                    "effective_american_odds": -145,
                    "effective_projected_prob": 0.66,
                    "effective_implied_prob": 0.5918,
                    "effective_edge": 0.0682,
                    "model_confidence": 0.75,
                    "data_quality": 0.93,
                    "bet_quality_score": 84.0,
                    "recommended_tier": "A",
                    "recommended_action": "Bettable now",
                    "fragility_bucket": "medium",
                    "selection_fallback_used": 0.0,
                    "market_blend_weight": 0.14,
                    "chosen_expression_stake": 22.0,
                },
                {
                    "event_name": "Test Event",
                    "fighter_a": "Eta",
                    "fighter_b": "Theta",
                    "fight_key": "eta||theta",
                    "chosen_value_expression": "Eta moneyline",
                    "effective_american_odds": +105,
                    "effective_projected_prob": 0.53,
                    "effective_implied_prob": 0.4878,
                    "effective_edge": 0.0422,
                    "model_confidence": 0.69,
                    "data_quality": 0.92,
                    "bet_quality_score": 78.0,
                    "recommended_tier": "B",
                    "recommended_action": "Watchlist",
                    "fragility_bucket": "low",
                    "selection_fallback_used": 0.0,
                    "market_blend_weight": 0.10,
                    "chosen_expression_stake": 18.0,
                },
                {
                    "event_name": "Test Event",
                    "fighter_a": "Iota",
                    "fighter_b": "Kappa",
                    "fight_key": "iota||kappa",
                    "chosen_value_expression": "Iota moneyline",
                    "effective_american_odds": -160,
                    "effective_projected_prob": 0.67,
                    "effective_implied_prob": 0.6154,
                    "effective_edge": 0.0546,
                    "model_confidence": 0.73,
                    "data_quality": 0.91,
                    "bet_quality_score": 82.0,
                    "recommended_tier": "A",
                    "recommended_action": "Bettable now",
                    "fragility_bucket": "low",
                    "selection_fallback_used": 0.0,
                    "market_blend_weight": 0.16,
                    "chosen_expression_stake": 19.0,
                },
                {
                    "event_name": "Test Event",
                    "fighter_a": "Huge",
                    "fighter_b": "Favorite",
                    "fight_key": "huge||favorite",
                    "chosen_value_expression": "Huge moneyline",
                    "effective_american_odds": -420,
                    "effective_projected_prob": 0.84,
                    "effective_implied_prob": 0.8077,
                    "effective_edge": 0.0323,
                    "model_confidence": 0.82,
                    "data_quality": 0.98,
                    "bet_quality_score": 90.0,
                    "recommended_tier": "A",
                    "recommended_action": "Bettable now",
                    "fragility_bucket": "low",
                    "selection_fallback_used": 0.0,
                    "market_blend_weight": 0.08,
                    "chosen_expression_stake": 20.0,
                },
            ]
        )

        parlays = build_parlay_board(report)

        self.assertEqual(len(parlays), 3)
        self.assertEqual(set(parlays["leg_count"].astype(int)), {3, 4, 5})
        self.assertFalse(parlays["legs"].astype(str).str.contains("Huge moneyline").any())
        self.assertTrue(parlays["american_odds"].astype(str).str.startswith("+").all())
        self.assertTrue(parlays["edge"].astype(str).str.endswith("%").all())

    def test_build_parlay_board_allows_strong_heavy_favorite_but_blocks_weak_one(self) -> None:
        report = pd.DataFrame(
            [
                {
                    "event_name": "Test Event",
                    "fighter_a": "Anchor",
                    "fighter_b": "Opponent",
                    "fight_key": "anchor||opponent",
                    "selection": "fighter_a",
                    "chosen_value_expression": "Anchor moneyline",
                    "effective_american_odds": -360,
                    "effective_projected_prob": 0.84,
                    "effective_implied_prob": 0.7826,
                    "effective_edge": 0.0574,
                    "model_confidence": 0.81,
                    "data_quality": 0.96,
                    "bet_quality_score": 89.0,
                    "recommended_tier": "A",
                    "recommended_action": "Bettable now",
                    "fragility_bucket": "low",
                    "selection_fallback_used": 0.0,
                    "market_blend_weight": 0.12,
                    "chosen_expression_stake": 25.0,
                    "support_count": 5,
                    "age_diff": 3.5,
                    "reach_diff": 4.0,
                    "grappling_diff": 1.4,
                    "support_signals": "younger, reach edge, grappling edge, gym edge",
                    "risk_flags": "",
                },
                {
                    "event_name": "Test Event",
                    "fighter_a": "Thin",
                    "fighter_b": "Favorite",
                    "fight_key": "thin||favorite",
                    "selection": "fighter_a",
                    "chosen_value_expression": "Thin moneyline",
                    "effective_american_odds": -355,
                    "effective_projected_prob": 0.81,
                    "effective_implied_prob": 0.7802,
                    "effective_edge": 0.0298,
                    "model_confidence": 0.66,
                    "data_quality": 0.91,
                    "bet_quality_score": 74.0,
                    "recommended_tier": "B",
                    "recommended_action": "Watchlist",
                    "fragility_bucket": "low",
                    "selection_fallback_used": 0.0,
                    "market_blend_weight": 0.12,
                    "chosen_expression_stake": 18.0,
                    "support_count": 2,
                    "age_diff": 1.0,
                    "reach_diff": 1.0,
                    "grappling_diff": 0.2,
                    "support_signals": "favorite profile",
                    "risk_flags": "",
                },
                {
                    "event_name": "Test Event",
                    "fighter_a": "Gamma",
                    "fighter_b": "Delta",
                    "fight_key": "gamma||delta",
                    "selection": "fighter_a",
                    "chosen_value_expression": "Gamma moneyline",
                    "effective_american_odds": +120,
                    "effective_projected_prob": 0.50,
                    "effective_implied_prob": 0.4545,
                    "effective_edge": 0.0455,
                    "model_confidence": 0.70,
                    "data_quality": 0.94,
                    "bet_quality_score": 80.0,
                    "recommended_tier": "A",
                    "recommended_action": "Bettable now",
                    "fragility_bucket": "low",
                    "selection_fallback_used": 0.0,
                    "market_blend_weight": 0.12,
                    "chosen_expression_stake": 24.0,
                },
                {
                    "event_name": "Test Event",
                    "fighter_a": "Epsilon",
                    "fighter_b": "Zeta",
                    "fight_key": "epsilon||zeta",
                    "selection": "fighter_a",
                    "chosen_value_expression": "Epsilon moneyline",
                    "effective_american_odds": -145,
                    "effective_projected_prob": 0.66,
                    "effective_implied_prob": 0.5918,
                    "effective_edge": 0.0682,
                    "model_confidence": 0.75,
                    "data_quality": 0.93,
                    "bet_quality_score": 84.0,
                    "recommended_tier": "A",
                    "recommended_action": "Bettable now",
                    "fragility_bucket": "medium",
                    "selection_fallback_used": 0.0,
                    "market_blend_weight": 0.14,
                    "chosen_expression_stake": 22.0,
                },
                {
                    "event_name": "Test Event",
                    "fighter_a": "Eta",
                    "fighter_b": "Theta",
                    "fight_key": "eta||theta",
                    "selection": "fighter_a",
                    "chosen_value_expression": "Eta moneyline",
                    "effective_american_odds": +105,
                    "effective_projected_prob": 0.53,
                    "effective_implied_prob": 0.4878,
                    "effective_edge": 0.0422,
                    "model_confidence": 0.69,
                    "data_quality": 0.92,
                    "bet_quality_score": 78.0,
                    "recommended_tier": "B",
                    "recommended_action": "Watchlist",
                    "fragility_bucket": "low",
                    "selection_fallback_used": 0.0,
                    "market_blend_weight": 0.10,
                    "chosen_expression_stake": 18.0,
                },
            ]
        )

        parlays = build_parlay_board(report)

        self.assertTrue(parlays["legs"].astype(str).str.contains("Anchor moneyline").any())
        self.assertFalse(parlays["legs"].astype(str).str.contains("Thin moneyline").any())


if __name__ == "__main__":
    unittest.main()
